apiVersion: argoproj.io/v1alpha1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: argocd
spec:
  repoURL: https://github.com/AVA-SheikAslam/Argo-CD.git
  targetRevision: HEAD
  selector:
    matchLabels:
      app: nginx
      destination:
    server: https://kubernetes.default.svc # Kubernetes cluster URL
    namespace: <target-namespace> # Namespace where the application will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sheikaslam/circleci:944e25bcdaf8a9ed5ba2d8c8ece4783a8d98f5c9
        ports:
        - containerPort: 80
