apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sheikaslam/circleci:944e25bcdaf8a9ed5ba2d8c8ece4783a8d98f5c9
        ports:
        - containerPort: 80
