apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deployment
  namespace: argocd
spec:
  project: default
  source: Argo-CD/Nginx
/deployment.yaml
    repoURL: https://github.com/your-repo
    path: path/to/deployment-files
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    namespace: nginx
    server: https://kubernetes-api-server
    name: "Ngnix-Stat-Webpg"
    namespace: "Nginx-ArgoCD"
  syncPolicy:
    automated:
      prune: true
